addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.10")
addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("com.github.sbt" % "sbt-jacoco" % "3.1.0")
addSbtPlugin("uk.co.josephearl" % "sbt-findbugs" % "2.5.0")
addSbtPlugin("com.github.sbt" % "sbt-cpd" % "2.0.0")